<?xml version="1.0"?>
<package format="3">

    <!-- Package Information -->
    <name>ov_data</name>
    <version>1.0.0</version>
    <description>
        Placeholder package for user-supplied datasets and ground-truth trajectories.
    </description>
    <url type="website">https://github.com/Yuantai-Z/FF-VIO-Init</url>
    <url type="bugtracker">https://github.com/Yuantai-Z/FF-VIO-Init/issues</url>
    <url type="repository">https://github.com/Yuantai-Z/FF-VIO-Init</url>

    <!-- Code Authors -->
    <author email="pgeneva@udel.edu">Patrick Geneva</author>
    <author email="tai0515nice@163.com">Yuantai-Z</author>
    <maintainer email="tai0515nice@163.com">Yuantai-Z</maintainer>

    <!-- Licensing -->
    <license>GNU General Public License v3.0</license>

    <!-- ROS 1 build tool. -->
    <buildtool_depend>catkin</buildtool_depend>

    <!-- Note the export is required to expose the executables -->
    <export>
        <build_type>catkin</build_type>
    </export>

</package>
